version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "el9-php82"
  schedule:
    interval: daily
